import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CAlert: (typeof import('@coreui/vue'))['CAlert'];
    CBadge: (typeof import('@coreui/vue'))['CBadge'];
    CBreadcrumb: (typeof import('@coreui/vue'))['CBreadcrumb'];
    CBreadcrumbItem: (typeof import('@coreui/vue'))['CBreadcrumbItem'];
    CButton: (typeof import('@coreui/vue'))['CButton'];
    CCard: (typeof import('@coreui/vue'))['CCard'];
    CCardBody: (typeof import('@coreui/vue'))['CCardBody'];
    CCardFooter: (typeof import('@coreui/vue'))['CCardFooter'];
    CCardHeader: (typeof import('@coreui/vue'))['CCardHeader'];
    CCloseButton: (typeof import('@coreui/vue'))['CCloseButton'];
    CCol: (typeof import('@coreui/vue'))['CCol'];
    CContainer: (typeof import('@coreui/vue'))['CContainer'];
    CDropdown: (typeof import('@coreui/vue'))['CDropdown'];
    CDropdownDivider: (typeof import('@coreui/vue'))['CDropdownDivider'];
    CDropdownHeader: (typeof import('@coreui/vue'))['CDropdownHeader'];
    CDropdownItem: (typeof import('@coreui/vue'))['CDropdownItem'];
    CDropdownMenu: (typeof import('@coreui/vue'))['CDropdownMenu'];
    CDropdownToggle: (typeof import('@coreui/vue'))['CDropdownToggle'];
    CFooter: (typeof import('@coreui/vue'))['CFooter'];
    CForm: (typeof import('@coreui/vue'))['CForm'];
    CFormCheck: (typeof import('@coreui/vue'))['CFormCheck'];
    CFormFeedback: (typeof import('@coreui/vue'))['CFormFeedback'];
    CFormFloating: (typeof import('@coreui/vue'))['CFormFloating'];
    CFormInput: (typeof import('@coreui/vue'))['CFormInput'];
    CFormLabel: (typeof import('@coreui/vue'))['CFormLabel'];
    CHeader: (typeof import('@coreui/vue'))['CHeader'];
    CHeaderBrand: (typeof import('@coreui/vue'))['CHeaderBrand'];
    CHeaderDivider: (typeof import('@coreui/vue'))['CHeaderDivider'];
    CHeaderNav: (typeof import('@coreui/vue'))['CHeaderNav'];
    CHeaderText: (typeof import('@coreui/vue'))['CHeaderText'];
    CImage: (typeof import('@coreui/vue'))['CImage'];
    CInputGroup: (typeof import('@coreui/vue'))['CInputGroup'];
    CInputGroupText: (typeof import('@coreui/vue'))['CInputGroupText'];
    CLink: (typeof import('@coreui/vue'))['CLink'];
    CListGroup: (typeof import('@coreui/vue'))['CListGroup'];
    CListGroupItem: (typeof import('@coreui/vue'))['CListGroupItem'];
    CModal: (typeof import('@coreui/vue'))['CModal'];
    CModalBody: (typeof import('@coreui/vue'))['CModalBody'];
    CModalFooter: (typeof import('@coreui/vue'))['CModalFooter'];
    CModalHeader: (typeof import('@coreui/vue'))['CModalHeader'];
    CNav: (typeof import('@coreui/vue'))['CNav'];
    CNavItem: (typeof import('@coreui/vue'))['CNavItem'];
    CNavLink: (typeof import('@coreui/vue'))['CNavLink'];
    CPagination: (typeof import('@coreui/vue'))['CPagination'];
    CPaginationItem: (typeof import('@coreui/vue'))['CPaginationItem'];
    CRow: (typeof import('@coreui/vue'))['CRow'];
    CSidebar: (typeof import('@coreui/vue'))['CSidebar'];
    CSidebarHeader: (typeof import('@coreui/vue'))['CSidebarHeader'];
    CSpinner: (typeof import('@coreui/vue'))['CSpinner'];
    CTable: (typeof import('@coreui/vue'))['CTable'];
    CTableBody: (typeof import('@coreui/vue'))['CTableBody'];
    CTableDataCell: (typeof import('@coreui/vue'))['CTableDataCell'];
    CTableHead: (typeof import('@coreui/vue'))['CTableHead'];
    CTableHeaderCell: (typeof import('@coreui/vue'))['CTableHeaderCell'];
    CTableRow: (typeof import('@coreui/vue'))['CTableRow'];
    CToast: (typeof import('@coreui/vue'))['CToast'];
    CToastBody: (typeof import('@coreui/vue'))['CToastBody'];
    CToastHeader: (typeof import('@coreui/vue'))['CToastHeader'];
    CToaster: (typeof import('@coreui/vue'))['CToaster'];
    CTabs: (typeof import('@coreui/vue'))['CTabs'];
    CTabList: (typeof import('@coreui/vue'))['CTabList'];
    CTab: (typeof import('@coreui/vue'))['CTab'];
    CTabContent: (typeof import('@coreui/vue'))['CTabContent'];
    CTabPanel: (typeof import('@coreui/vue'))['CTabPanel'];
    CPopover: (typeof import('@coreui/vue'))['CPopover'];
  }
}
export {};
